Create Database CSE_3A_237

Create table DEPOSIT(
	ACTNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2),
	ADATE DATETIME
);

select * from DEPOSIT

insert into DEPOSIT(ACTNO,CNAME,BNAME,AMOUNT,ADATE) VALUES (109,'MINU','POWAI',7000,'1995-8-10');

Create table BRANCH(
	BNAME VARCHAR(50),
	CITY VARCHAR(50)
);

select * from BRANCH;
insert into BRANCH (BNAME,CITY) values ('POWAI','BOMBAY');

Create table CUSTOMERS(
	CNAME VARCHAR(50),
	CITY VARCHAR(50)
);

select * from CUSTOMERS

insert into CUSTOMERS(CNAME,CITY) VALUES('NAREN','BOMBAY');

Create table BORROW(
	LOANNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2)

);

select * from BORROW

insert into BORROW(LOANNO,CNAME,BNAME,AMOUNT) VALUES(481,'KRANTI','NEHRU PLACE',3000);